sudo: false
language: ruby
cache: bundler

rvm:
  - 1.9.3
  - 2.0.0
  - 2.2.0

bundler_args: --without integration

before_install:
  - gem install rubygems-update
  - update_rubygems

script:
  - bundle exec rake
